FROM {{cookiecutter.base_docker}}
#RUN cd / && git clone https://github.com/microsoft/vcpkg && ./vcpkg/bootstrap-vcpkg.sh
#RUN cd /vcpkg && ./vcpkg integrate install
#RUN ln -s /vcpkg/vcpkg /usr/bin/vcpkg
#RUN apt update -y && apt install -y libboost-dev catch
#RUN vcpkg update
#RUN vcpkg install stb cppzmq ms-gsl

# find_path(STB_INCLUDE_DIRS "stb.h")
# add_executable(main main.cpp)
# target_include_directories(main PRIVATE ${STB_INCLUDE_DIRS})

